spring:
  application:
    name: GroceryApi

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/grocerydb
    username: appuser
    password: AHexOO45qLjWNNj
    driver-class-name: com.mysql.cj.jdbc.Driver


